//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScoopenAPI.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAcademicDetail
    {
        public int Id { get; set; }
        public Nullable<int> StudentId { get; set; }
        public Nullable<int> DeptId { get; set; }
        public string DocumentOne { get; set; }
        public string DocumentTwo { get; set; }
        public string DocumentThree { get; set; }
        public string DocumentFour { get; set; }
        public string DocumentFive { get; set; }
    }
}
