//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScoopenAPI.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblJobDescription
    {
        public int Id { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public Nullable<int> RoundId { get; set; }
        public Nullable<int> SkillSetId { get; set; }
        public Nullable<int> PackageId { get; set; }
        public Nullable<int> DeptId { get; set; }
        public Nullable<int> JobTitleId { get; set; }
        public string JobDescription { get; set; }
        public Nullable<int> EligibilityId { get; set; }
        public Nullable<int> DesignationId { get; set; }
        public Nullable<System.DateTime> ScheduleDateTime { get; set; }
        public string Location { get; set; }
        public string Comments { get; set; }
    }
}
