//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScoopenAPI.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblOrder
    {
        public Nullable<int> OrderId { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> TemplateId { get; set; }
        public string TemplateName { get; set; }
        public int Quantity { get; set; }
    
        public virtual OrderStatu OrderStatu { get; set; }
        public virtual tblUpload tblUpload { get; set; }
        public virtual tblUserInfo tblUserInfo { get; set; }
    }
}
