//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScoopenAPI.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblResetPasswordRequest
    {
        public System.Guid Id { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<System.DateTime> ResetRequestDateTime { get; set; }
    }
}
