//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScoopenAPI.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSelectionProcess
    {
        public int Id { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public Nullable<int> DepartmentId { get; set; }
        public Nullable<int> JobDescriptionId { get; set; }
        public Nullable<int> StudentId { get; set; }
        public Nullable<bool> IsSelected { get; set; }
        public Nullable<bool> RoundOne { get; set; }
        public Nullable<bool> RoundTwo { get; set; }
        public Nullable<bool> RoundThree { get; set; }
        public string Comment { get; set; }
    }
}
