//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScoopenAPI.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblVehicleOwner
    {
        public int DriverId { get; set; }
        public Nullable<int> UserId { get; set; }
        public string Pancard { get; set; }
        public string License { get; set; }
        public string Location { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<decimal> AvgRating { get; set; }
        public Nullable<int> NoOfTrips { get; set; }
        public Nullable<int> VehicleId { get; set; }
    
        public virtual tblUser tblUser { get; set; }
        public virtual tblVehicle tblVehicle { get; set; }
    }
}
