//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScoopenAPI.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblVehicle
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblVehicle()
        {
            this.tblVehicleOwners = new HashSet<tblVehicleOwner>();
        }
    
        public int VehicleId { get; set; }
        public string VehicleNumber { get; set; }
        public string Insurance { get; set; }
        public string Rc { get; set; }
        public string Permit { get; set; }
        public string VehicleImage { get; set; }
        public Nullable<int> VehicleTypeId { get; set; }
    
        public virtual tblVehicleType tblVehicleType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblVehicleOwner> tblVehicleOwners { get; set; }
    }
}
